### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rednaw** [rednaw/projectDragon#5]
## Mail
- [ ] Create list of email addresses 
- [ ] Create email template with link to login page
- [ ] Link to login page should be unique for each mail: add encrypted email address as parameter eg. `https://sigokta.com/signin?q=sfdsfs867`
- [ ] Create script that processes list of addresses and sends an email for each

## Login
- [ ] Buy domain
- [ ] Configure login page to use new domain, eg `https://sigokta.com/signin`
- [ ] Let login page accept parameter for unique id (encrypted email address)
- [ ] Add counter++ for each aspect of login page using unique id

For example `https://sigokta.com/signin?q=sfdsfs867`
- When loaded (click on link in mail) counter `sfdsfs867_link_clicked`  is increased
- When characters are typed in username field counter `sfdsfs867_username_typed` is increased
- When characters are typed in passwword field counter `sfdsfs867_password_typed` is increased
- When sign-in button is pressed counter `sfdsfs867_login_clicked` is increased

## Dashboard
- [ ] Show table with a row for each email address in list, columns are `email address`, `link_clicked`, `username_typed`, `password_typed` and `login_clicked` 

## Encryption
- [ ] Choose JS library for symmetric encryption (key stays local, is not committed)
- [ ] Used by mail sender to create unique links with encrypted mail address as parameter
- [ ] Used by dashboard to decrypt mail addresses and create table rows
